name: test_build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Prerequisites (Zig)
        run: sudo snap install zig --classic --beta
      - name: Zig fmt check
        run: zig fmt build.zig src --check
      - name: Run Zig Tests
        run: zig build test
